from fastapi import FastAPI
import yt_dlp
import requests
import re

app = FastAPI()

def clean_vtt_text(vtt_content):
    """
    VTT (Subtitle File) se kachra (Timestamps, Tags) hatane ka logic
    """
    lines = vtt_content.split('\n')
    cleaned_lines = []
    seen_lines = set()

    for line in lines:
        # 1. Header aur Metadata hatao
        if 'WEBVTT' in line or 'Kind:' in line or 'Language:' in line:
            continue
        # 2. Timestamps hatao (00:00:00.000 --> ...)
        if '-->' in line:
            continue
        # 3. Tags hatao (<c>, <00:00:01> etc)
        text = re.sub(r'<[^>]+>', '', line).strip()
        
        # 4. Empty lines aur Duplicate lines hatao
        if text and text not in seen_lines:
            cleaned_lines.append(text)
            seen_lines.add(text)
            
    return " ".join(cleaned_lines)

@app.get("/")
def home():
    return {"status": "Online", "engine": "yt-dlp Pro"}

@app.get("/api/transcript")
def get_yt_transcript(url: str):
    try:
        # yt-dlp Options: Hame video nahi, sirf 'Metadata' chahiye
        ydl_opts = {
            'skip_download': True,       # Video download mat karna
            'writeautomaticsub': True,   # Auto-generated captions uthao
            'writesub': True,            # Manual captions bhi uthao
            'subtitleslangs': ['en', 'hi', 'en-orig', 'hi-latn'], # English/Hindi prefer karo
            'quiet': True,
            'no_warnings': True
        }

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=False)
            
            # 1. Check for Captions (Auto or Manual)
            # Pehle Automatic check karo (Kyunki error wahi aa raha tha)
            captions = info.get('automatic_captions') or info.get('subtitles')
            
            if not captions:
                return {
                    "status": "error", 
                    "message": "❌ Bhai is video ka koi bhi text data (Audio-to-Text) YouTube ke server par nahi hai."
                }

            # 2. Best Language Select Karna (Priority: English -> Hindi)
            # yt-dlp data structure: {'en': [{'url': '...', 'ext': 'json3'}], ...}
            lang_code = 'en'
            if 'en' not in captions and 'hi' in captions:
                lang_code = 'hi'
            elif 'en' not in captions:
                # Agar En/Hi nahi hai to jo pehla mile wo utha lo
                lang_code = list(captions.keys())[0]

            # 3. Subtitle URL nikalna (VTT format is easiest to clean)
            # Hum specific format 'vtt' dhundenge
            subs_list = captions[lang_code]
            sub_url = None
            
            for sub in subs_list:
                # Prefer VTT for easy cleaning
                if sub.get('ext') == 'vtt':
                    sub_url = sub['url']
                    break
            
            # Agar VTT nahi mila, to pehla wala lelo (usually json3 or srv1)
            if not sub_url:
                sub_url = subs_list[0]['url']

            # 4. URL se Text Download karna
            response = requests.get(sub_url)
            raw_text = response.text

            # 5. Text Cleaning
            final_text = clean_vtt_text(raw_text)
            
            # 6. Summary Logic (Simple frequency based)
            words = final_text.split()
            summary = " ".join(words[:50]) + "..." # Fallback summary

            # Formatting Response
            separator = "\n" + "="*40 + "\n"
            final_output = (
                f"🎥 VIDEO TRANSCRIPT (Engine: yt-dlp)\n"
                f"🔗 Video ID: {info.get('id')}\n"
                f"🗣️ Language: {lang_code}\n"
                f"{separator}"
                f"{final_text}"
                f"\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                f"⚡ Generated by @lakshitpatidar\n"
                f"━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            )

            return {
                "status": "success",
                "video_title": info.get('title'),
                "transcript_text": final_output,
                "data": final_output # For MacroDroid
            }

    except Exception as e:
        return {"status": "error", "message": str(e)}
            
